"""new fields in user model

Revision ID: 362019351724
Revises: 70dbbd5c073a
Create Date: 2020-11-06 03:30:01.949233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362019351724'
down_revision = '70dbbd5c073a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
